// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 口座振替に関する情報です。お支払方法が口座振替の顧客のみ利用できます。
 * @export
 * @interface AccountTransfer
 */
export interface AccountTransfer {
    /**
     * このObjectの種別を示します。ここでは必ず`account_transfer`が入ります。
     * @type {string}
     * @memberof AccountTransfer
     */
    object?: AccountTransferModelObjectEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum AccountTransferModelObjectEnum {
    AccountTransfer = 'account_transfer'
}

