// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 銀行振込に関する情報です。お支払方法が銀行振込の顧客のみ利用できます。 初回請求前は振込先口座が未割当のため、`object`以外は空で返却されます。
 * @export
 * @interface BankTransfer
 */
export interface BankTransfer {
    /**
     * 振込先口座番号です。未割当の場合は空で返却されます。
     * @type {string}
     * @memberof BankTransfer
     */
    accountNumber?: string;
    /**
     * 振込先銀行名です。未割当の場合は空で返却されます。
     * @type {string}
     * @memberof BankTransfer
     */
    bankName?: string;
    /**
     * 振込先銀行支店名です。未割当の場合は空で返却されます。
     * @type {string}
     * @memberof BankTransfer
     */
    branchName?: string;
    /**
     * このObjectの種別を示します。ここでは必ず`bank_transfer`が入ります。
     * @type {string}
     * @memberof BankTransfer
     */
    object?: BankTransferModelObjectEnum;
    /**
     * 振込先口座種別です。`current`(当座)、`saving`(普通)の2種類のうちどちらかが指定されます。未割当の場合は空で返却されます。
     * @type {string}
     * @memberof BankTransfer
     */
    type?: BankTransferTypeEnum;
    /**
     * 振込先口座名義です。必ず`ｴﾑｴﾌｹﾂｻｲ(ｶ`になります。未割当の場合は空で返却されます。
     * @type {string}
     * @memberof BankTransfer
     */
    holderName?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum BankTransferModelObjectEnum {
    BankTransfer = 'bank_transfer'
}
/**
 * @export
 * @enum {string}
 */
export enum BankTransferTypeEnum {
    Current = 'current',
    Saving = 'saving'
}

