// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Billing,
    Pagination,
} from './';

/**
 * @export
 * @interface BillingsList
 */
export interface BillingsList {
    /**
     * 請求一覧です。
     * @type {Array<Billing>}
     * @memberof BillingsList
     */
    items?: Array<Billing>;
    /**
     * このObjectの種別を示します。ここでは必ず `list`が設定されます。
     * @type {string}
     * @memberof BillingsList
     */
    object?: BillingsListModelObjectEnum;
    /**
     * @type {Pagination}
     * @memberof BillingsList
     */
    pagination?: Pagination;
}

/**
 * @export
 * @enum {string}
 */
export enum BillingsListModelObjectEnum {
    List = 'list'
}

