// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 請求される条件です。審査結果に関わらずすべて請求する(`all`)、審査通過の取引のみ請求する(`passed`)のうちから選択してください。<br> 空の場合は管理画面の「請求対象の設定」で設定された条件で登録されます。請求対象について詳しくは[こちら](https://support.mfkessai.co.jp/hc/ja/articles/900000168566)を参照ください。
 * @export
 * @enum {string}
 */
export enum BillingCondition {
    Passed = 'passed',
    All = 'all'
}

