// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Customer,
    Destination,
} from './';

/**
 * @export
 * @interface CreateCustomerResponse
 */
export interface CreateCustomerResponse {
    /**
     * @type {Customer}
     * @memberof CreateCustomerResponse
     */
    customer?: Customer;
    /**
     * @type {Destination}
     * @memberof CreateCustomerResponse
     */
    destination?: Destination;
}
