// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CreditFacility,
    Pagination,
} from './';

/**
 * @export
 * @interface CreditFacilitiesList
 */
export interface CreditFacilitiesList {
    /**
     * 与信枠一覧です。
     * @type {Array<CreditFacility>}
     * @memberof CreditFacilitiesList
     */
    items?: Array<CreditFacility>;
    /**
     * このObjectの種別を示します。ここでは必ず `list`が設定されます。
     * @type {string}
     * @memberof CreditFacilitiesList
     */
    object?: CreditFacilitiesListModelObjectEnum;
    /**
     * @type {Pagination}
     * @memberof CreditFacilitiesList
     */
    pagination?: Pagination;
}

/**
 * @export
 * @enum {string}
 */
export enum CreditFacilitiesListModelObjectEnum {
    List = 'list'
}

