// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 請求先情報です。
 * @export
 * @interface CustomerPayloadDestination
 */
export interface CustomerPayloadDestination {
    /**
     * 都道府県・市区町村・番地です。必ず都道府県名から始めてください。
     * @type {string}
     * @memberof CustomerPayloadDestination
     */
    address1: string;
    /**
     * 建物名・部屋番号などです。
     * @type {string}
     * @memberof CustomerPayloadDestination
     */
    address2?: string;
    /**
     * 請求書をメール送付する際のCCメールアドレスです。最大で4つまで指定できます。
     * @type {Array<string>}
     * @memberof CustomerPayloadDestination
     */
    ccEmails?: Array<string>;
    /**
     * 担当者の部署名です。
     * @type {string}
     * @memberof CustomerPayloadDestination
     */
    department?: string;
    /**
     * メールアドレスです。email形式で指定してください。
     * @type {string}
     * @memberof CustomerPayloadDestination
     */
    email: string;
    /**
     * 担当者氏名です。
     * @type {string}
     * @memberof CustomerPayloadDestination
     */
    name?: string;
    /**
     * 担当者名カナです。全角カタカナで入力してください。
     * @type {string}
     * @memberof CustomerPayloadDestination
     */
    nameKana?: string;
    /**
     * 電話番号です。ハイフン有無は任意になります。
     * @type {string}
     * @memberof CustomerPayloadDestination
     */
    tel: string;
    /**
     * 担当者の役職です。
     * @type {string}
     * @memberof CustomerPayloadDestination
     */
    title?: string;
    /**
     * 郵便番号です。ハイフン有無は任意になります。但しハイフン無しで登録されますと、請求書にもハイフン無しで記載されます。
     * @type {string}
     * @memberof CustomerPayloadDestination
     */
    zipCode: string;
}
