// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 顧客更新情報です。顧客更新時に利用します。
 * @export
 * @interface CustomerUpdatePayload
 */
export interface CustomerUpdatePayload {
    /**
     * 顧客に付与できる任意の顧客番号です。MF KESSAIが発番する顧客IDをとは別で、売り手様が独自に管理する識別子を登録することができます。 ただし、売り手様の所有する顧客間で一意である必要があります。指定がないか空文字の場合は更新されません。
     * @type {string}
     * @memberof CustomerUpdatePayload
     */
    number?: string;
}
