// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 顧客審査申請情報です。顧客審査申請で利用します。
 * @export
 * @interface CustomerExaminationPayload
 */
export interface CustomerExaminationPayload {
    /**
     * 都道府県・市区町村・番地です。必ず都道府県名から始めてください。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    address1: string;
    /**
     * 建物名・部屋番号などです。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    address2?: string;
    /**
     * 希望与信額です。審査通過の場合に付与される与信枠の金額になります。現在与信枠が適用中の場合は、その与信額以下の金額は指定できません。
     * @type {number}
     * @memberof CustomerExaminationPayload
     */
    amount: number;
    /**
     * 事業内容です。顧客の主なサービス、商材などを記載してください。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    businessDescription?: string;
    /**
     * 事業所区分です。法人(`corporate`)または、個人(`individual`)で指定してください。不明な場合は空にしてください。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    businessType?: CustomerExaminationPayloadBusinessTypeEnum;
    /**
     * 法人番号です。事業所区分(`business_type`)が法人(`corporate`)の場合にのみ指定してください。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    corporateNumber?: string;
    /**
     * 顧客審査を申請する顧客のIDです。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    customerId: string;
    /**
     * メールアドレスです。email形式で指定してください。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    email: string;
    /**
     * 希望取引登録期間終了日です。この日付まで対象の与信枠を利用して取引登録ができます。 直近三ヶ月の月末のみ指定できます。ただし当月残りの営業日数が審査に要する2日を下回っている場合は、当月末は指定できません。
     * @type {Date}
     * @memberof CustomerExaminationPayload
     */
    endDate: Date;
    /**
     * 顧客審査に利用できるその他情報を記載できます。<br>Sandbox環境において顧客審査で任意の結果を指定するためにこの値を用います。詳しくは[マジックナンバーを利用した審査結果の操作](#environment_magic_number)を参照ください。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    remark?: string;
    /**
     * 代表者氏名です。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    representativeName?: string;
    /**
     * 電話番号です。ハイフン有無は任意になります。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    tel: string;
    /**
     * 顧客企業のwebサイトです。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    website?: string;
    /**
     * 郵便番号です。ハイフン有無は任意になります。但しハイフン無しで登録されますと、請求書にもハイフン無しで記載されます。
     * @type {string}
     * @memberof CustomerExaminationPayload
     */
    zipCode: string;
}

/**
 * @export
 * @enum {string}
 */
export enum CustomerExaminationPayloadBusinessTypeEnum {
    Corporate = 'corporate',
    Individual = 'individual'
}

