// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TaxRateType,
} from './';

/**
 * 消費税です。
 * @export
 * @interface DeductionTax
 */
export interface DeductionTax {
    /**
     * 消費税額です。
     * @type {number}
     * @memberof DeductionTax
     */
    amount?: number | null;
    /**
     * @type {TaxRateType}
     * @memberof DeductionTax
     */
    rateType?: TaxRateType;
}
