// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DeductionTaxableBillingCharge,
    DeductionTaxableConvenienceBilling,
    DeductionTaxablePosting,
} from './';

/**
 * 課税対象の控除金額とその内訳です。郵送料と月額基本料が課税対象となります。
 * @export
 * @interface DeductionTaxable
 */
export interface DeductionTaxable {
    /**
     * 課税対象の控除金額です。
     * @type {number}
     * @memberof DeductionTaxable
     */
    amount?: number | null;
    /**
     * 月額基本料金です。
     * @type {number}
     * @memberof DeductionTaxable
     */
    basicMonthlyCharge?: number | null;
    /**
     * @type {DeductionTaxableBillingCharge}
     * @memberof DeductionTaxable
     */
    billingCharge?: DeductionTaxableBillingCharge;
    /**
     * @type {DeductionTaxablePosting}
     * @memberof DeductionTaxable
     */
    posting?: DeductionTaxablePosting;
    /**
     * @type {DeductionTaxableConvenienceBilling}
     * @memberof DeductionTaxable
     */
    convenienceBilling?: DeductionTaxableConvenienceBilling;
}
