// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 請求先です。一つの顧客に対して複数作成することができます。請求先の情報を利用して請求書送付を行います。 <aside class=\"info\">請求先は更新ができません。更新したい場合は新規登録をしてご利用ください。</aside>
 * @export
 * @interface Destination
 */
export interface Destination {
    /**
     * 都道府県・市区町村・番地です。必ず都道府県名から始めてください。
     * @type {string}
     * @memberof Destination
     */
    address1?: string;
    /**
     * 建物名・部屋番号などです。
     * @type {string}
     * @memberof Destination
     */
    address2?: string;
    /**
     * CCメールアドレスです。最大4件まで登録できます。
     * @type {Array<string>}
     * @memberof Destination
     */
    ccEmails?: Array<string>;
    /**
     * 請求先が登録された日時を示します。
     * @type {Date}
     * @memberof Destination
     */
    createdAt?: Date;
    /**
     * 顧客IDです。一意の識別子として自動で付与されます。
     * @type {string}
     * @memberof Destination
     */
    customerId?: string;
    /**
     * 担当者の部署名です。
     * @type {string}
     * @memberof Destination
     */
    department?: string;
    /**
     * メールアドレスです。email形式で指定してください。
     * @type {string}
     * @memberof Destination
     */
    email?: string;
    /**
     * 請求先IDです。一意の識別子として自動で付与されます。
     * @type {string}
     * @memberof Destination
     */
    id?: string;
    /**
     * 担当者名です。
     * @type {string}
     * @memberof Destination
     */
    name?: string;
    /**
     * 担当者名カナです。全角カタカナで入力してください。
     * @type {string}
     * @memberof Destination
     */
    nameKana?: string;
    /**
     * このObjectの種別を示します。ここでは必ず`destination`が入ります。
     * @type {string}
     * @memberof Destination
     */
    object?: DestinationModelObjectEnum;
    /**
     * 電話番号です。ハイフン有無は任意になります。
     * @type {string}
     * @memberof Destination
     */
    tel?: string;
    /**
     * 担当者の役職です。
     * @type {string}
     * @memberof Destination
     */
    title?: string;
    /**
     * 請求先URIです。すべてのリソースで一意の識別子として自動で付与されます。
     * @type {string}
     * @memberof Destination
     */
    uri?: string;
    /**
     * 郵便番号です。ハイフン有無は任意になります。但しハイフン無しで登録されますと、請求書にもハイフン無しで記載されます。
     * @type {string}
     * @memberof Destination
     */
    zipCode?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum DestinationModelObjectEnum {
    Destination = 'destination'
}

