// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 請求書送付方法です。郵送(posting) またはメール送付(email)のいずれかを指定してください。
 * @export
 * @enum {string}
 */
export enum InvoiceDeliveryMethod {
    Posting = 'posting',
    Email = 'email'
}

