// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * エラー内容の詳細です。4xxのエラーコードとともに返却されます。
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * エラーコードです。それぞれの説明については、[エラーコード](https://mfkessai.co.jp/developer/v2/docs/#error_codes)を参照してください。
     * @type {string}
     * @memberof ModelError
     */
    code?: ModelErrorCodeEnum;
    /**
     * エラー発生原因に関する情報です。
     * @type {string}
     * @memberof ModelError
     */
    message?: string;
    /**
     * 何らかの値に関連するエラーの場合その値が入ります。
     * @type {string}
     * @memberof ModelError
     */
    param?: string;
    /**
     * エラー種別です。
     * @type {string}
     * @memberof ModelError
     */
    type?: ModelErrorTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ModelErrorCodeEnum {
    UnavailableSeller = 'unavailable_seller',
    NotFound = 'not_found',
    RequestCanceled = 'request_canceled',
    AlreadyExists = 'already_exists',
    SellerSettingRequired = 'seller_setting_required',
    InvalidJsonFormat = 'invalid_json_format',
    InvalidAfter = 'invalid_after',
    InvalidBefore = 'invalid_before',
    InvalidLimit = 'invalid_limit',
    OutOfRangeByAfter = 'out_of_range_by_after',
    OutOfRangeByBefore = 'out_of_range_by_before',
    InvalidAmountPerTaxRateTypeAmount = 'invalid_amount_per_tax_rate_type_amount',
    InvalidAmountPerTaxRateTypeTaxRateType = 'invalid_amount_per_tax_rate_type_tax_rate_type',
    InvalidCreatedAtFrom = 'invalid_created_at_from',
    InvalidCreatedAtTo = 'invalid_created_at_to',
    InvalidCustomerDestination = 'invalid_customer_destination',
    InvalidCustomerHasAlert = 'invalid_customer_has_alert',
    InvalidCustomerId = 'invalid_customer_id',
    InvalidCustomerName = 'invalid_customer_name',
    InvalidCustomerNumber = 'invalid_customer_number',
    InvalidCustomerPaymentMethod = 'invalid_customer_payment_method',
    InvalidDestinationAddress1 = 'invalid_destination_address1',
    InvalidDestinationAddress2 = 'invalid_destination_address2',
    InvalidDestinationCcEmails = 'invalid_destination_cc_emails',
    InvalidDestinationDepartment = 'invalid_destination_department',
    InvalidDestinationEmail = 'invalid_destination_email',
    InvalidDestinationId = 'invalid_destination_id',
    InvalidDestinationName = 'invalid_destination_name',
    InvalidDestinationNameKana = 'invalid_destination_name_kana',
    InvalidDestinationTel = 'invalid_destination_tel',
    InvalidDestinationTitle = 'invalid_destination_title',
    InvalidDestinationZipCode = 'invalid_destination_zip_code',
    InvalidCustomerExaminationId = 'invalid_customer_examination_id',
    InvalidCustomerExaminationAddress1 = 'invalid_customer_examination_address1',
    InvalidCustomerExaminationAddress2 = 'invalid_customer_examination_address2',
    InvalidCustomerExaminationAmount = 'invalid_customer_examination_amount',
    InvalidCustomerExaminationAmountWithBalance = 'invalid_customer_examination_amount_with_balance',
    InvalidCustomerExaminationBusinessDescription = 'invalid_customer_examination_business_description',
    InvalidCustomerExaminationBusinessType = 'invalid_customer_examination_business_type',
    InvalidCustomerExaminationCorporateNumber = 'invalid_customer_examination_corporate_number',
    InvalidCustomerExaminationEmail = 'invalid_customer_examination_email',
    InvalidCustomerExaminationEndDate = 'invalid_customer_examination_end_date',
    InvalidCustomerExaminationRemark = 'invalid_customer_examination_remark',
    InvalidCustomerExaminationRepresentativeName = 'invalid_customer_examination_representative_name',
    InvalidCustomerExaminationStatus = 'invalid_customer_examination_status',
    InvalidCustomerExaminationTel = 'invalid_customer_examination_tel',
    InvalidCustomerExaminationWebsite = 'invalid_customer_examination_website',
    InvalidCustomerExaminationZipCode = 'invalid_customer_examination_zip_code',
    InvalidCreditFacilityEndDateFrom = 'invalid_credit_facility_end_date_from',
    InvalidCreditFacilityEndDateTo = 'invalid_credit_facility_end_date_to',
    InvalidCreditFacilityId = 'invalid_credit_facility_id',
    InvalidCreditFacilityStartDateFrom = 'invalid_credit_facility_start_date_from',
    InvalidCreditFacilityStartDateTo = 'invalid_credit_facility_start_date_to',
    InvalidTransactionAmount = 'invalid_transaction_amount',
    InvalidTransactionAmountsPerTaxRateType = 'invalid_transaction_amounts_per_tax_rate_type',
    InvalidTransactionBilling = 'invalid_transaction_billing',
    InvalidTransactionBillingCondition = 'invalid_transaction_billing_condition',
    InvalidTransactionDetails = 'invalid_transaction_details',
    InvalidTransactionDetailAmount = 'invalid_transaction_detail_amount',
    InvalidTransactionDetailDescription = 'invalid_transaction_detail_description',
    InvalidTransactionDetailQuantity = 'invalid_transaction_detail_quantity',
    InvalidTransactionDetailTaxIncludedType = 'invalid_transaction_detail_tax_included_type',
    InvalidTransactionDetailTaxRateType = 'invalid_transaction_detail_tax_rate_type',
    InvalidTransactionDetailUnitPrice = 'invalid_transaction_detail_unit_price',
    InvalidTransactionDate = 'invalid_transaction_date',
    InvalidTransactionDateFrom = 'invalid_transaction_date_from',
    InvalidTransactionDateTo = 'invalid_transaction_date_to',
    InvalidTransactionDueDate = 'invalid_transaction_due_date',
    InvalidTransactionDuplicateInvoiceDeliveryMethod = 'invalid_transaction_duplicate_invoice_delivery_method',
    InvalidTransactionInvoiceDeliveryMethods = 'invalid_transaction_invoice_delivery_methods',
    InvalidTransactionIssueDate = 'invalid_transaction_issue_date',
    InvalidTransactionId = 'invalid_transaction_id',
    InvalidTransactionNumber = 'invalid_transaction_number',
    InvalidTransactionStatus = 'invalid_transaction_status',
    NotCancelableTransactionStatus = 'not_cancelable_transaction_status',
    InvalidBillingDueDateFrom = 'invalid_billing_due_date_from',
    InvalidBillingDueDateTo = 'invalid_billing_due_date_to',
    InvalidBillingId = 'invalid_billing_id',
    InvalidBillingIssueDateFrom = 'invalid_billing_issue_date_from',
    InvalidBillingIssueDateTo = 'invalid_billing_issue_date_to',
    InvalidBillingStatus = 'invalid_billing_status',
    InvalidBillingUnpaid = 'invalid_billing_unpaid',
    InvalidPayoutDateFrom = 'invalid_payout_date_from',
    InvalidPayoutDateTo = 'invalid_payout_date_to',
    InvalidPayoutId = 'invalid_payout_id',
    InvalidPayoutStatus = 'invalid_payout_status',
    InvalidPayoutTransactionId = 'invalid_payout_transaction_id'
}
/**
 * @export
 * @enum {string}
 */
export enum ModelErrorTypeEnum {
    AlreadyExisitsError = 'already_exisits_error',
    ConflictOperationError = 'conflict_operation_error',
    InvalidArgumentError = 'invalid_argument_error',
    NotFoundError = 'not_found_error',
    RateLimitError = 'rate_limit_error',
    RequestCanceled = 'request_canceled',
    UnavailableSeller = 'unavailable_seller',
    SellerSettingRequired = 'seller_setting_required'
}

