// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Pagination,
    PayoutRefund,
} from './';

/**
 * @export
 * @interface PayoutRefundsList
 */
export interface PayoutRefundsList {
    /**
     * 返金一覧です。
     * @type {Array<PayoutRefund>}
     * @memberof PayoutRefundsList
     */
    items?: Array<PayoutRefund>;
    /**
     * このObjectの種別を示します。ここでは必ず `list`が設定されます。
     * @type {string}
     * @memberof PayoutRefundsList
     */
    object?: PayoutRefundsListModelObjectEnum;
    /**
     * @type {Pagination}
     * @memberof PayoutRefundsList
     */
    pagination?: Pagination;
}

/**
 * @export
 * @enum {string}
 */
export enum PayoutRefundsListModelObjectEnum {
    List = 'list'
}

