// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Pagination,
    PayoutTransaction,
} from './';

/**
 * @export
 * @interface PayoutTransactionsList
 */
export interface PayoutTransactionsList {
    /**
     * 債権一覧です。
     * @type {Array<PayoutTransaction>}
     * @memberof PayoutTransactionsList
     */
    items?: Array<PayoutTransaction>;
    /**
     * このObjectの種別を示します。ここでは必ず `list`が設定されます。
     * @type {string}
     * @memberof PayoutTransactionsList
     */
    object?: PayoutTransactionsListModelObjectEnum;
    /**
     * @type {Pagination}
     * @memberof PayoutTransactionsList
     */
    pagination?: Pagination;
}

/**
 * @export
 * @enum {string}
 */
export enum PayoutTransactionsListModelObjectEnum {
    List = 'list'
}

