// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 売り手さまへの振込後に発生したキャンセルに伴う返金です。
 * @export
 * @interface PayoutRefund
 */
export interface PayoutRefund {
    /**
     * 返金金額です。
     * @type {number}
     * @memberof PayoutRefund
     */
    amount?: number;
    /**
     * 手数料の金額です。
     * @type {number}
     * @memberof PayoutRefund
     */
    commissionAmount?: number | null;
    /**
     * 顧客IDです。この返金が紐づく顧客を示します。
     * @type {string}
     * @memberof PayoutRefund
     */
    customerId?: string;
    /**
     * 返金IDです。一意の識別子として自動で付与されます。
     * @type {string}
     * @memberof PayoutRefund
     */
    id?: string;
    /**
     * このObjectの種別を示します。ここでは必ず`payout_refund`が入ります。
     * @type {string}
     * @memberof PayoutRefund
     */
    object?: PayoutRefundModelObjectEnum;
    /**
     * 返金が含まれる振込のIDです。
     * @type {string}
     * @memberof PayoutRefund
     */
    payoutId?: string;
    /**
     * 取引IDです。この返金が紐づく取引を示します。
     * @type {string}
     * @memberof PayoutRefund
     */
    transactionId?: string;
    /**
     * 返金URIです。すべてのリソースで一意の識別子として自動で付与されます。
     * @type {string}
     * @memberof PayoutRefund
     */
    uri?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum PayoutRefundModelObjectEnum {
    PayoutRefund = 'payout_refund'
}

