// tslint:disable
/**
 * MF KESSAI API v2
 * MF KESSAI REST API
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: api.support@mfkessai.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AmountPerTaxRateType,
    BillingCondition,
    InvoiceDeliveryMethod,
    TransactionDetailPayload,
} from './';

/**
 * 取引登録情報です。取引登録で利用します。
 * @export
 * @interface TransactionPayload
 */
export interface TransactionPayload {
    /**
     * 取引の税込合計金額です。各課税種別毎の税込金額(amounts_per_tax_rate_type)の合計である必要があります。また、負の値を指定することはできません。
     * @type {number}
     * @memberof TransactionPayload
     */
    amount: number;
    /**
     * 各課税種別毎の税込の合計金額です。各課税種別の取引明細行の小計を合計した値になっていなければなりません。
     * @type {Array<AmountPerTaxRateType>}
     * @memberof TransactionPayload
     */
    amountsPerTaxRateType: Array<AmountPerTaxRateType>;
    /**
     * @type {BillingCondition}
     * @memberof TransactionPayload
     */
    billingCondition?: BillingCondition;
    /**
     * 取引日です。売り手様と顧客の間で取引を行った日付を指定してください。
     * @type {Date}
     * @memberof TransactionPayload
     */
    date: Date;
    /**
     * 請求先IDです。取引の請求先を指定してください。
     * @type {string}
     * @memberof TransactionPayload
     */
    destinationId: string;
    /**
     * 支払期限です。
     * @type {Date}
     * @memberof TransactionPayload
     */
    dueDate: Date;
    /**
     * 請求書送付方法です。郵送(posting) またはメール送付(email)のうちから少なくとも１つを指定してください。どちらも選択された場合、どちらの方法でも送付されます。 また、各取引で指定しなかった送付方法でも、請求にまとまった取引のうちでその送付方法を選択しているものがあれば、そちらの送付方法も採用されます。
     * @type {Array<InvoiceDeliveryMethod>}
     * @memberof TransactionPayload
     */
    invoiceDeliveryMethods: Array<InvoiceDeliveryMethod>;
    /**
     * 請求書発行日です。請求書が発行される日付を指定します。指定した日付が営業日でない場合は翌営業日になります。また、請求書送付日については[こちら](https://support.mfkessai.co.jp/hc/ja/articles/360012259673-%E8%AB%8B%E6%B1%82%E6%9B%B8%E7%99%BA%E8%A1%8C%E6%97%A5)を参照ください。
     * @type {Date}
     * @memberof TransactionPayload
     */
    issueDate: Date;
    /**
     * 取引に付与できる任意の取引番号です。MF KESSAIが自動で付与する取引IDとは別で、売り手様が独自に管理する識別子を登録することができます。ただし、売り手様の所有する取引間で一意である必要があります。
     * @type {string}
     * @memberof TransactionPayload
     */
    number: string;
    /**
     * 取引明細行です。
     * @type {Array<TransactionDetailPayload>}
     * @memberof TransactionPayload
     */
    transactionDetails: Array<TransactionDetailPayload>;
}
